### ISSUE TITLE
enable custom job problem on 20130807

### ISSUE THREAD

**Issue by skybook888** [MStr3am/NEMO#109]
when enabled costom jobs the size appearence of the baby classes would be desabled
the baby classes looks as big as the ordinary classes

**Comment by lelouch22** [comment]
Are you using an updated NEMO? becuase that issue was fixed a long time ago.

**Comment by skybook888** [comment]
my nemo is 20151204

**Comment by MStr3am** [comment]
The one you are referring to is old please use an updated version of NEMO. There was a crash happening for that client date which is fixed now.

**Comment by vBrenth** [comment]
Hello Neo, custom job are getting error on 2013-12-23 clients .

https://rathena.org/board/topic/104796-gravity-error-when-enabled-custom-jobs-is-enabled/

**Comment by vBrenth** [comment]
@MStr3am i know this is close :D but its still happening :'|

**Comment by MStr3am** [comment]
I am not seeing any error for 2013-12-23 client or 2013-08-07 client. login is working just fine.
are you sure you are using a proper client for patching?

haven't checked the dislocation effect yet. will do soon.
